// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aux_My_Cov_Trob
Rcpp::List aux_My_Cov_Trob(arma::mat x, SEXP center, bool wtMissing, arma::vec wt, bool cor, double nu, int maxit, double tol);
RcppExport SEXP _robFitConGraph_aux_My_Cov_Trob(SEXP xSEXP, SEXP centerSEXP, SEXP wtMissingSEXP, SEXP wtSEXP, SEXP corSEXP, SEXP nuSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type wtMissing(wtMissingSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< bool >::type cor(corSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(aux_My_Cov_Trob(x, center, wtMissing, wt, cor, nu, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// mahalanobis_fast_aux
arma::vec mahalanobis_fast_aux(const arma::mat& x, const arma::vec& center, const arma::mat& cov);
RcppExport SEXP _robFitConGraph_mahalanobis_fast_aux(SEXP xSEXP, SEXP centerSEXP, SEXP covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cov(covSEXP);
    rcpp_result_gen = Rcpp::wrap(mahalanobis_fast_aux(x, center, cov));
    return rcpp_result_gen;
END_RCPP
}
// myfitConGraphC
List myfitConGraphC(NumericMatrix amat, NumericMatrix S, double tol);
RcppExport SEXP _robFitConGraph_myfitConGraphC(SEXP amatSEXP, SEXP SSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type amat(amatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(myfitConGraphC(amat, S, tol));
    return rcpp_result_gen;
END_RCPP
}
// regMLEdirect_loop
Rcpp::List regMLEdirect_loop(arma::mat& X, arma::mat amat, arma::mat S_old, arma::mat& S_new, arma::vec& mu_old, arma::vec& mu_new, const double df, const double tol);
RcppExport SEXP _robFitConGraph_regMLEdirect_loop(SEXP XSEXP, SEXP amatSEXP, SEXP S_oldSEXP, SEXP S_newSEXP, SEXP mu_oldSEXP, SEXP mu_newSEXP, SEXP dfSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type amat(amatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S_old(S_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type S_new(S_newSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu_old(mu_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu_new(mu_newSEXP);
    Rcpp::traits::input_parameter< const double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(regMLEdirect_loop(X, amat, S_old, S_new, mu_old, mu_new, df, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robFitConGraph_aux_My_Cov_Trob", (DL_FUNC) &_robFitConGraph_aux_My_Cov_Trob, 8},
    {"_robFitConGraph_mahalanobis_fast_aux", (DL_FUNC) &_robFitConGraph_mahalanobis_fast_aux, 3},
    {"_robFitConGraph_myfitConGraphC", (DL_FUNC) &_robFitConGraph_myfitConGraphC, 3},
    {"_robFitConGraph_regMLEdirect_loop", (DL_FUNC) &_robFitConGraph_regMLEdirect_loop, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_robFitConGraph(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
