# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_My_Cov_Trob <- function(x, center, wtMissing, wt, cor, nu, maxit, tol) {
    .Call(`_robFitConGraph_aux_My_Cov_Trob`, x, center, wtMissing, wt, cor, nu, maxit, tol)
}

mahalanobis_fast_aux <- function(x, center, cov) {
    .Call(`_robFitConGraph_mahalanobis_fast_aux`, x, center, cov)
}

myfitConGraphC <- function(amat, S, tol = 0.000001) {
    .Call(`_robFitConGraph_myfitConGraphC`, amat, S, tol)
}

regMLEdirect_loop <- function(X, amat, S_old, S_new, mu_old, mu_new, df, tol = 0.000001) {
    .Call(`_robFitConGraph_regMLEdirect_loop`, X, amat, S_old, S_new, mu_old, mu_new, df, tol)
}

